"""
forecast_engine.py
------------------
Recursive autoregressive forecasting engine for Philippine food prices.

For each (region, commodity) series, this module builds feature vectors
month-by-month by feeding prior predicted log-prices back as lag inputs.
Conformal prediction intervals are applied at every step.

Feature engineering must exactly mirror 03_model.py to ensure
predictions are on the same scale as the trained XGBoost models.

v2: Accepts a per-month ONI DataFrame (from oni_generator.py) instead
    of a single constant ONI value, enabling realistic ENSO cycling.
"""

import numpy as np
import pandas as pd

# ── Constants (must match 03_model.py exactly) ──────────────────────
COASTAL_REGIONS = {
    "Region III", "Region IV-A", "Region IV-B",
    "Region VII", "Region VIII", "Region IX", "Region XI", "Region XII"
}
CORRIDOR_REGIONS = {"Region III", "Region IV-A"}

ENSO_DUMMY_COLS = ["enso_phase_La Nina", "enso_phase_Neutral"]

# Legacy constants kept for backward compatibility
SCENARIO_ONI = {
    "El Nino":  1.5,
    "Neutral":  0.0,
    "La Nina": -1.5,
}
SCENARIO_PHASE = {
    "El Nino":  "El Nino",
    "Neutral":  "Neutral",
    "La Nina":  "La Nina",
}


def _get_lag(price_history: dict, target_date: pd.Timestamp, months: int) -> float:
    """Return log_price from `months` before target_date, or NaN if missing."""
    dt = target_date - pd.DateOffset(months=months)
    return price_history.get(pd.Timestamp(dt.year, dt.month, 1), np.nan)


def build_feature_vector(
    region: str,
    target_date: pd.Timestamp,
    price_history: dict,
    oni: float,
    oni_lag_3: float,
    oni_lag_6: float,
    enso_phase: str,
    region_enc: int,
    comm_mean: float,
    comm_std: float,
    feature_cols: list,
) -> np.ndarray:
    """
    Build a single row feature vector for one forecasting step.

    Parameters
    ----------
    price_history : dict {pd.Timestamp -> float}
        Known log_price values (actual + previously predicted).
        Must contain at least 12 months of history before target_date.
    oni, oni_lag_3, oni_lag_6 : float
        ONI values for the current month and its lags, sourced from
        the synthetic ONI series generated by oni_generator.py.
    enso_phase : str
        ENSO phase string for current month ("El Nino", "La Nina", "Neutral").
    feature_cols : list
        Ordered list of feature names matching 03_model.py exactly.
    """
    month = target_date.month
    year  = target_date.year

    # ── Price lags ──────────────────────────────────────────────────
    lag_1  = _get_lag(price_history, target_date, 1)
    lag_2  = _get_lag(price_history, target_date, 2)
    lag_3  = _get_lag(price_history, target_date, 3)
    lag_6  = _get_lag(price_history, target_date, 6)
    lag_12 = _get_lag(price_history, target_date, 12)

    # ── YoY change ──────────────────────────────────────────────────
    price_yoy = (lag_1 - lag_12) if not (np.isnan(lag_1) or np.isnan(lag_12)) else 0.0

    # ── Rolling 3-month volatility (std of lags 1–3) ───────────────
    vol_vals   = [v for v in [lag_1, lag_2, lag_3] if not np.isnan(v)]
    price_vol3 = float(np.std(vol_vals)) if len(vol_vals) >= 2 else 0.0

    # ── Rolling 6-month trend (mean of lags 1–6) ───────────────────
    trend_vals   = [_get_lag(price_history, target_date, i) for i in range(1, 7)]
    trend_vals   = [v for v in trend_vals if not np.isnan(v)]
    price_trend6 = float(np.mean(trend_vals)) if trend_vals else (lag_1 if not np.isnan(lag_1) else 0.0)

    # ── Cyclic month encoding ───────────────────────────────────────
    month_sin = float(np.sin(2 * np.pi * month / 12))
    month_cos = float(np.cos(2 * np.pi * month / 12))

    # ── ONI × season interactions ───────────────────────────────────
    oni_x_month_sin = oni * month_sin
    oni_x_month_cos = oni * month_cos

    # ── Seasonal supply flags ───────────────────────────────────────
    typhoon_season    = float(month in [6, 7, 8, 9, 10, 11])
    fishing_ban       = float(month in [11, 12, 1, 2, 3])
    is_coastal        = float(region in COASTAL_REGIONS)
    is_luzon_corridor = float(region in CORRIDOR_REGIONS)
    is_january        = float(month == 1)

    # ── ENSO dummies (El Nino is the dropped baseline) ─────────────
    enso_phase_la_nina = float(enso_phase == "La Nina")
    enso_phase_neutral = float(enso_phase == "Neutral")

    feat = {
        "price_lag_1":        lag_1  if not np.isnan(lag_1)  else 0.0,
        "price_lag_2":        lag_2  if not np.isnan(lag_2)  else 0.0,
        "price_lag_3":        lag_3  if not np.isnan(lag_3)  else 0.0,
        "price_lag_6":        lag_6  if not np.isnan(lag_6)  else 0.0,
        "price_lag_12":       lag_12 if not np.isnan(lag_12) else 0.0,
        "price_yoy":          price_yoy,
        "price_vol3":         price_vol3,
        "price_trend6":       price_trend6,
        "oni":                oni,
        "oni_lag_3":          oni_lag_3,
        "oni_lag_6":          oni_lag_6,
        "oni_x_month_sin":    oni_x_month_sin,
        "oni_x_month_cos":    oni_x_month_cos,
        "month_sin":          month_sin,
        "month_cos":          month_cos,
        "year":               float(year),
        "typhoon_season":     typhoon_season,
        "fishing_ban":        fishing_ban,
        "is_coastal":         is_coastal,
        "is_luzon_corridor":  is_luzon_corridor,
        "is_january":         is_january,
        "region_enc":         float(region_enc),
        "comm_mean":          comm_mean,
        "comm_std":           comm_std,
        "enso_phase_La Nina": enso_phase_la_nina,
        "enso_phase_Neutral": enso_phase_neutral,
    }

    return np.array([feat[c] for c in feature_cols], dtype=np.float32)


def recursive_forecast(
    region: str,
    commodity: str,
    commodity_group: str,
    conformal_reg,
    seed_log_prices: dict,
    start_date: pd.Timestamp,
    end_date: pd.Timestamp,
    oni_df: pd.DataFrame,
    region_enc: int,
    comm_mean: float,
    comm_std: float,
    feature_cols: list,
) -> pd.DataFrame:
    """
    Recursively forecast monthly prices from start_date to end_date.

    Each predicted log_price is fed back into the history dict so
    subsequent steps can use it as a lag feature.

    Parameters
    ----------
    oni_df : pd.DataFrame
        Date-indexed DataFrame with columns: oni, enso_phase,
        oni_lag_3, oni_lag_6. Generated by oni_generator.generate_oni_series().
        Must cover every month from start_date to end_date.

    Returns
    -------
    pd.DataFrame with columns: date, pred, lower, upper, oni, enso_phase
    """
    price_history = dict(seed_log_prices)  # working copy
    dates   = pd.date_range(start=start_date, end=end_date, freq="MS")
    records = []

    for dt in dates:
        # ── Look up this month's climate values ────────────────────
        oni_row    = oni_df.loc[dt] if dt in oni_df.index else None
        oni_val    = float(oni_row["oni"])       if oni_row is not None else 0.0
        oni_lag3   = float(oni_row["oni_lag_3"]) if oni_row is not None else 0.0
        oni_lag6   = float(oni_row["oni_lag_6"]) if oni_row is not None else 0.0
        enso_phase = str(oni_row["enso_phase"])  if oni_row is not None else "Neutral"

        fv = build_feature_vector(
            region=region,
            target_date=dt,
            price_history=price_history,
            oni=oni_val,
            oni_lag_3=oni_lag3,
            oni_lag_6=oni_lag6,
            enso_phase=enso_phase,
            region_enc=region_enc,
            comm_mean=comm_mean,
            comm_std=comm_std,
            feature_cols=feature_cols,
        )

        fv_2d = fv.reshape(1, -1)
        pred_log, pi = conformal_reg.predict_interval(fv_2d)

        pred_log_val = float(pred_log[0])
        lower_val    = float(np.exp(pi[0, 0, 0]))
        upper_val    = float(np.exp(pi[0, 1, 0]))
        pred_val     = float(np.exp(pred_log_val))

        records.append({
            "date":       dt,
            "pred":       round(pred_val,  4),
            "lower":      round(lower_val, 4),
            "upper":      round(upper_val, 4),
            "oni":        round(oni_val,   3),
            "enso_phase": enso_phase,
        })

        # Feed predicted log_price back into history for next step
        price_history[dt] = pred_log_val

    return pd.DataFrame(records)
